# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



title: Arya Ajeev
description: This is Arya Ajeev's personal website
github_username: Arya-Ajeev
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _publications
  - assets
  - assets/bib

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Arya Ajeev"
  avatar : "/assets/images/IMG_8001.jpeg"
  bio    : "Ph.D. Candidate @ University of Maine"
  location: "Orono, Maine"
  email : "arya.ajeeva@maine.edu"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "www.linkedin.com/in/arya-ajeev"

    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"   # Workaround icon
      url: "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C20&as_ylo=2025&q=arya+ajeev&oq=Arya+"

    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ParthanOlikkal"

    - label: "CV"
      icon: "fas fa-file-pdf"
      url: "/assets/docs/Parthan_CV.pdf"

collections:
  publications:
    output: true
    permalink: /publication/:name/

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      css: "assets/css/custom.css"
